---
title: "AE 18: Exam 02 review" 
subtitle: ""
date: "2021-10-20"
output: 
  html_document: 
    fig_height: 3
    fig_width: 6
    theme: readable
    code_folding: hide
---

```{r include = F}
knitr::opts_chunk$set(warning = F, 
                      message = F)
```


## Announcements

- Exam 02 - Thu, Oct 21 - Fri, Oct 22
  - Covers Weeks 05 - 08
  - Similar format as Exam 01

- No labs on Thu, Oct 21

  
- Team Feedback #1 due Wed, Oct 27 at 11:59pm
  - Check inbox for email from Teammates to fill out feedback
  - This feedback is just graded on completion

- [Project proposal](https://sta210-fa21.netlify.app/project/#project-proposal) due **Friday, October 29 at 11:59pm**
  
- Ed Discussion for this class: https://edstem.org/us/courses/8350/discussion/750243


## Statistics experience 

- [Click here](https://sta210-fa21.netlify.app/hw/stats-experience.html) for instructions. 
  - due **December 3 at 11:59pm** on Gradescope.
  

### Upcoming events

**HackDuke Code for Good - October 23 - 24**

- Free event but registration required
- Go to [2021.hackduke.org](https://2021.hackduke.org/) for more information. 


**Duke Datathon - November 6 - 7**

[Click here](https://dukeml.org/datathon/) for more information

##  AE 18: Exam 02 review

- Go to the ae-18-[GITHUB USERNAME] repo in the GitHub course organization: https://github.com/sta210-fa21

- Access the RStudio Docker containers at https://vm-manage.oit.duke.edu/containers

- See the [Lab 01 instructions](https://sta210-fa21.netlify.app/labs/lab-01-ikea.html) for details on cloning the repo and starting a new project in RStudio.

