---
title: "Prepare: Week 02"
output: 
  html_document:
    css: "prepare.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## For August 30

**Note:** All required prepare activities are due **<u>by the beginning of class (3:30p)</u>** on the specified date.

### Required 

`r emo::ji("movie_camera")` Watch [Simple Linear Regression: Introduction](https://warpwire.duke.edu/w/VykFAA/)

- [Slides](https://sta210-fa21.netlify.app/slides/03-slr-intro.html)

### Optional 

`r emo::ji("memo")` Take Prep Quiz 00 under Tests & Quizzes in Sakai.

- Going forward, prepare quizzes will be required. This quiz is optional to give you an opportunity to practice using Sakai quizzes. 

`r emo::ji("book")` [Introductin to Modern Statistics (IMS) Section 3.1 - 3.4.1: Introduction to linear models](https://openintro-ims.netlify.app/intro-linear-models.html)

## For September 01

`r emo::ji("movie_camera")` Watch [SLR: Foundation for inference](https://warpwire.duke.edu/w/1ywFAA/)

- [Slides](https://sta210-fa21.netlify.app/slides/04-slr-foundation.html)

`r emo::ji("movie_camera")` Watch [SLR: Inference for coefficients](https://warpwire.duke.edu/w/4SwFAA/)

- [Slides](https://sta210-fa21.netlify.app/slides/04-slr-coef-inf.html)

### Optional 



`r emo::ji("book")` [IMS Section 8.1.3: Inference for linear models - mathematical model](https://openintro-ims.netlify.app/inference-reg.html#mathslope)

`r emo::ji("book")` [Deriving the least squares estimates for simple linear regression](https://github.com/sta210-fa19/supplemental-notes/blob/master/slr-derivations.pdf)



