---
title: "HW 03:Multiple linear regression"
subtitle: "due Wednesday, October 15 at 11:59pm"
output: 
  tufte::tufte_html:
    css: "sta210-hw.css"
    tufte_variant: "envisioned"
    highlight: pygments
    fig_height: 4
    fig_width: 6
    toc: true
    toc_depth: 1
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE,
                      message=FALSE,
                      eval  = FALSE)
```


Instructions will be released when the homework is assigned. 

<!--
# Introduction 

In this assignment, you'll use regression analysis to explore the growth rate for young adult lemurs at the Duke Lemur Center. 

## Learning goals

In this assignment, you will...

- practice the regression analysis workflow - from exploratory data analysis through drawing conclusions 
- write results and conclusions in narrative form. 
- gain experience analyzing data through an open-ended analysis process.

# Getting started 

-   Go to the [**sta210-fa21**](https://www.github.com/sta210-fa21) organization on GitHub. Click on the repo with the prefix **hw-03**. It contains the starter documents you need to complete the lab.

- Clone the repo and start a new project in RStudio. See the [Lab 01 instructions](https://sta210-fa21.netlify.app/labs/lab-01-ikea.html) for details on cloning a repo, starting a new R project and configuring git. 


## Packages 

You will use the following packages in this assignment. 

```{r}
library(tidyverse)
library(broom)
library(knitr) 
```

```{r echo=F}
derby <- read_csv("data/derbyplus.csv")
derby <- derby %>%
  mutate(year=year-1896)
```

# Exercises

## Part 1: Kentucky Derby 

This section of the homework contains short answer questions focused on concepts. Some of these questions may also require short chunks of code to produce the output needed to answer the question. All answers should be written in complete sentences. 

The Kentucky Derby is a 1.25 mile horse race held annually at the Churchill Downs race track in Louisville, Kentucky. The data used to fit the regression model in this analysis includes information about 122 derbies held 1896 to 2017. The analysis focuses on the following variables: 

- `year`: year of race recorded as number of years since 1896
    - e.g.: 2017 is recorded as `2017 - 1896 = 121`
- `condition`: condition of the track - fast, good, and slow.
    - "good" includes the official designations "good" and "dusty"
    - "slow" includes the official designations "slow", "heavy", "muddy", and "sloppy"
- `starters`: number of horses who raced
- `startersCent`: mean-centered value of `starters` calculated as (`starters` - 14)
- `speed`: average speed of the winner (in feet per second)

Below is a regression model using the main effects `year`, `condition`, `starters`, and  the interaction `year * condition` to explain variation in `speed`.  The statistical model 


```{r echo=F}
model <- lm(speed ~ year + starters + condition + year*condition, data=derby)
kable(tidy(model, conf.int = T), digits = 3)
```

1. Write the equation of the statistical model being estimated by the regression equation. 

2. Interpret the effect of year on the speed of the winner for 
  - Fast track conditions.
  - Slow track conditions.

3. State the estimate and p-value associated with the following analysis tasks. If the information is not available in the regression table, state how you could refit the regression model to get the desired information. 

  - (a) Effect of year is the same for fast track conditions and good track conditions. 
4. What is the p-value for the test that the mean winning speed is the same for fast track conditions and good track conditions, given *year* and *starters* both equal 0? 

5. What is the p-value for the test that the slope of year is the same for fast track conditions and good track conditions (holding year and starters constant)? 

6. What is the 95% confidence interval for the amount by which the slope of year for slow track conditions exceeds the slope of year for fast track conditions?

7. Let's conduct the nested F test to test whether the slope of year is the same for all three condition types. In other words, we wish to test the hypotheses

$$ \begin{aligned} &H_0: \beta_5 = \beta_6 = 0 \\
&H_a: \text{ at least one }\beta_j \text{ is not 0}\end{aligned}$$

The residual sum of squares for the model shown above is 50.076 with 115 degrees of freedom. The residual sum of squares for the model that does not include the interaction terms between year and condition is 54.307 with 117 degrees of freedom. Calculate the F test statistic and p-value for this test. What is your conclusion? 


## Part 2: Data Analysis

The *Data Analysis* section of homework contains open-ended data analysis questions. Your response should be neatly organized and read as a complete narrative. This means that in addition to addressing the question there should also be exploratory data analysis and an analysis of the model assumptions. In short, these questions should be treated as "mini-projects".

8. For this portion, you will use the `housing` data you started analyzing in [Lab 04](https://www2.stat.duke.edu/courses/Spring19/sta210.001/labs/lab-04-mlr.html). Use the code below to load the data and prepare the data.

```{r eval = F}
houses <- read_csv("data/KingCountyHouses.csv")
houses <- houses %>%
  filter(bedrooms <= 5 ) %>%
  mutate(floorsCat = as.factor(floors), 
         sqftCent = sqft - mean(sqft), 
         bedroomsCent = bedrooms - mean(bedrooms),
         bathroomsCent = bathrooms-mean(bathrooms),
         logprice = log(price))
```

Fit a regression model with `logprice` as the response and `floorsCat`, `sqftCent`, `bedroomsCent`, `bathroomsCent`, and `waterfront` as predictor variables. In your analysis, include the following: 

- Briefly explain why we should use the log-transformed version of `price` instead of the original version of the variable. 
- Describe the relationship between a house's price and square footage (holding all else constant), including the appropriate confidence intervals. 
- Describe how the expected price differs based on the number of floors in the house (holding all else constant). Include discussion about whether or not the differences are statistically significant.
- Consider the interaction between `waterfront` and `bedroomsCent`. Is this interaction significant? If so, describe how the relationship between `price` and `bedroomsCent` changes based on whether the house has a waterfront view. (*You do not need show a check of the model assumptions for this model if you've checked the model assumptions for the model without the interaction.*)

As usual, be sure to include exploratory data analysis and an analysis of the model assumptions.

## Extra Credit (5 pts)

To best satisfy the modeling assumptions, we should log-transform both the price and the square footage. Build a simple linear regression model of `logprice` versus `logsqft`, the log-transformed version of `sqft`. Display the model output. (*You do not need show a check of the model assumptions for this model.*)

- Interpret the intercept in terms of price. Does the intercept have a meaningful interpretation? Briefly explain. 
- Based on this model, what is the expected change in price when the square footage is multiplied by a factor of 1.1? 


# Grading

| **Total** | **70** |
|-------------------------------------------------------------|:--:|
| Questions 1 - 7 | 30 |
| Question 8 | 30 |
| Documents complete and neatly organized (Markdown and knitted documents) | 5 |
| Answers written in complete sentences | 3 |
| Regular and informative commit messages | 2 |


## Acknowledgement

The data used in this assignment was obtained from [https://github.com/proback/BYSH](https://github.com/proback/BYSH).

-->