---
title: "Exam 01 Instructions"
subtitle: "Thursday, Sep 23 at 9a - Friday, Sep 24 at 11:59p"
output: 
  tufte::tufte_html:
    css: "sta210-exam.css"
    tufte_variant: "envisioned"
    highlight: pygments
    toc: true
    toc_depth: 1
---

# General instructions

Exam 01 will be released on Thu, Sep 23 at 9a and must be completed by Fri, Sep 24 at 11:59p. You will find the **exam-01-** repo on GitHub by the Thursday at 9a. 

The exam will consist of two parts: 

`r emo::ji("one")` Multiple choice/ short answer questions on Sakai test and quizzes. This portion may only be submitted one time.
  

`r emo::ji("two")` Data analysis in RStudio and submitted in Gradescope (like a usual lab and homework)

- You must submit a PDF document to Gradescope that corresponds to an`.Rmd` file on your GitHub repository in order to receive credit for this portion of the exam.

**Both portions must be completed and submitted by Friday, Sep 24 at 11:59p**. Late work will only be accepted in the case of of extenuating circumstances and notification from your academic dean. 

# Academic Integrity

By taking this exam, you pledge to uphold the Duke Community Standard:

-   I will not lie, cheat, or steal in my academic endeavors;
-   I will conduct myself honorably in all my endeavors; and
-   I will act if the Standard is compromised.

# Rules & Notes

-   This is an individual assignment. Everything in your repository is for your eyes only.
-   You may not collaborate or communicate anything about this exam to **anyone** except the instructor. For example, you may not communicate with other students, the TAs, or post/solicit help on the internet, email or via any other method of communication.
- The exam is open-book, open-note, so you may use any materials from class as you take the exam.
- No TA office hours will be held Thu, Sep 23 - Fri, Sep 24 
- You may not email the TAs questions about the exam.
- Ed Discussion will be inactive Thu, Sep 23 - Fri, Sep 24.
- If you have questions, email Professor Tackett with  "STA 210 Exam" in the subject line or attend Professor Tackett's office hours (Thursday, 10a - 11a).

# Submission

`r emo::ji("white_check_mark")` The answers to the multiple choice/short answer questions should be submitted under *Test & Quizzes* in Sakai (same place you take prep quizzes)

`r emo::ji("white_check_mark")` The PDF document for the data analysis portion must be uploaded to Gradescope. 

- Mark the pages associated with each section. If
any answer for a section spans multiple pages, mark all pages. 

- Make sure to associate the “Workflow & formatting" section with the first page. **Failure to mark the pages in Gradescope may result in point deductions.**

-  Make sure that your uploaded PDF document matches your `.Rmd` and the PDF in your GitHub repository exactly. Points will be deducted for documents that are not reproducible. 