---
title: "Lab 06: Logistic regression"
subtitle: "due Monday, November 08 at 11:59pm"
output: 
  tufte::tufte_html:
    css: "./sta210-labs.css"
    tufte_variant: "envisioned"
    highlight: pygments
    fig_height: 10
    toc: true
    toc_depth: 1
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE, 
                      message=FALSE,
                      eval=FALSE)
```

# Learning goals

By the end of the lab you will be able to...

- Use logistic regression to explore the relationship between a binary response variable and multiple predictor variables
- Conduct exploratory data analysis for logistic regression 
- Interpret coefficients of logistic regression model
- Compare models and select the one that best fits the data

#  The data


 
## Data

The General Social Survey (GSS) has been used to measure trends in attitudes and behaviors in American society since 1972. In addition to collecting demographic information, the survey includes questions used to gauge attitudes about government spending priorities, confidence in institutions, lifestyle, and many other topics. A full description of the survey may be found [here](http://www.norc.org/Research/Projects/Pages/general-social-survey.aspx).

The data for this lab are from the 2016 General Social Survey. The original data set contains 2867 observations and 935 variables. Given the size of the dataset, we'll load it into the R Markdown file from the internet rather than keeping it in the data folder of our RStudio project.

We will use the following variables in the lab: 

- `natmass`: Respondent's answer to the following prompt:

    "We are faced with many problems in this country, none of which can be solved easily or inexpensively. I’m going to name some of these problems, and for each one I’d like you to tell me whether you think we’re spending too much money on it, too little money, or about the right amount...are we spending too much, too little, or about the right amount on mass transportation?"

- `age`: Age in years.
- `sex`: Sex recorded as *male* or *female*
- `sei10`: Socioeconomic index from 0 to 100
- `region`: Region where interview took place
- `polviews`: Respondent's answer to the following prompt: 

    "We hear a lot of talk these days about liberals and conservatives. I’m going to show you a seven-point scale on which the political views that people might hold are arranged from extremely liberal - point 1 - to extremely conservative - point 7. Where would you place yourself on this scale?"

The data are in `gss2016.csv` in the `data` folder.

# Exercises 

The goal of today's lab is to analyze data to examine the relationship between US adults' political views and attitudes towards government spending on mass transportation projects.

## Part I: Exploratory data analysis

1. The goal of the analysis is to analyze factors potentially associated with satisfaction with the current spending on mass transportation. Create a new variable that is equal to "1" if a respondent said spending on mass transportation is about right and "0" otherwise. The make a plot of the new variable.

2. Recode `polviews` so it is a factor variable type with levels that are in an order that is consistent with question on the survey. *Note how the categories are spelled in the data.*

    Make a plot of the distribution of `polviews`. Which political view occurs most frequently in this data set?

3. Make a plot displaying the relationship between satisfaction with mass transportation spending  and political views. Use the plot to describe the relationship between a person's political views and whether they are satisfied with spending on mass transportation. 

4. We'd like to use `age` as a quantitative variable in your model; however, it is currently a character data type because some observations are coded as `"89 or older"`. Recode `age` so that is a numeric variable. *Note: Before making the variable numeric, you will need to replace the values `"89 or older"` with a single value.*

## Part II: Logistic regression model

5. Briefly explain why we should use a logistic regression model to predict the odds a randomly selected person is satisfied with spending on mass transportation. 

6. Let's start by fitting a model using the demographic factors - `age`, `sex`, `sei10`, and `region` - to predict the odds a person is satisfied with spending on mass transportation. Make any necessary adjustments to the variables so the intercept will have a meaningful interpretation.

7. Interpret the intercept in the context of the data. 

8. Consider the relationship between age and one's opinion about spending on mass transportation. Interpret the coefficient of age in terms of the **odds** of being satisfied with spending on mass transportation.

9. Now let's see whether a person's political views has a significant impact on their odds of being satisfied with spending on mass transportation, after accounting for the demographic factors. 

    Conduct a drop-in-deviance test to determine if `polviews` is a significant predictor of attitude towards spending on mass transportation. State the null and alternative hypotheses in words, display all relevant code and output, and state your conclusion in the context of the problem.

10. Use the model selected in the previous exercise to describe the relationship (if any) between one's political views and their attitude towards spending on mass transportation. Be sure your answer includes the interpretation of the model coefficients and associated hypothesis tests or confidence intervals used to support your response. 

# Submission

- **Select <u>one</u> team member to upload the team's PDF submission to Gradescope.** 
- Be sure to mark every team member's name on Gradescope.
- Associate the "Workflow & formatting" graded section with the first page of your PDF, and mark the page associated with each exercise. If any answer spans multiple pages, then mark all pages.

**There should only be <u>one</u> submission per team on Gradescope.**

# Grading (50 pts)

| Component | Points |
|:----------|:-------|
| Ex 1 - 10    | 40   |
| Model diagnostics activity (individual score) | 5 |
| Workflow & formatting     | 5 |   

**Grading notes**:

-   The "Workflow & formatting" grade is to assess the reproducible workflow and team work. This includes having at least one meaningful commit by each team member and updating the name and date in the YAML.

There should only be <u>one</u> submission per team on Gradescope.